"""First migration

Revision ID: 9609610396a5
Revises: 
Create Date: 2023-09-18 13:10:22.796871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9609610396a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('studio', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True, default=20),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
